# Generated by Django 2.2 on 2019-11-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('comment',),
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('ingredient_id', models.IntegerField()),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('units', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='recipe')),
                ('servings', models.CharField(max_length=10)),
                ('time', models.IntegerField()),
                ('instructions', models.TextField()),
                ('dietary_requirement', models.CharField(max_length=200)),
                ('cuisine', models.ManyToManyField(to='recipefinderApp.Cuisine')),
                ('ingredients', models.ManyToManyField(to='recipefinderApp.Ingredient')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
