# Generated by Django 2.2 on 2019-11-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipefinderApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='comments',
            field=models.ManyToManyField(to='recipefinderApp.Comments'),
        ),
    ]
