# Generated by Django 2.2.7 on 2019-12-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipefinderApp', '0004_auto_20191128_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='cooking_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
