# Generated by Django 2.2.7 on 2019-12-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipefinderApp', '0007_auto_20191204_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='cuisine',
            field=models.ManyToManyField(to='recipefinderApp.Cuisine'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='diet',
            field=models.ManyToManyField(to='recipefinderApp.Diet'),
        ),
    ]
