# Generated by Django 2.2.7 on 2019-12-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipefinderApp', '0009_auto_20191204_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nick_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
