# Generated by Django 2.2.7 on 2019-12-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipefinderApp', '0010_profile_nick_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cooking_time',
            field=models.ManyToManyField(to='recipefinderApp.Cooktime'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cuisine',
            field=models.ManyToManyField(to='recipefinderApp.Cuisine'),
        ),
        migrations.AddField(
            model_name='profile',
            name='diet',
            field=models.ManyToManyField(to='recipefinderApp.Diet'),
        ),
        migrations.AddField(
            model_name='profile',
            name='metric',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Preferences',
        ),
    ]
